### ISSUE TITLE
How do I handle error?

### ISSUE THREAD

**Issue by shd101wyy** [jonschlinkert/markdown-toc#48]
Thanks for your awesome library ;)

My question is that: 

For example, I created 2 toc blocks like below 
```markdown

<!-- toc -->
- [hahaha](#hahaha)
<!-- tocstop -->

<!-- toc -->
- [hahaha](#hahaha)
<!-- tocstop -->

# hahaha
### yoooo
```

then I called `toc.insert` and I get the exception `Uncaught Error: markdown-toc only supports one Table of Contents per file.`.

If there any way to handle such errors in callback function instead of try/catch?

Thank you

**Comment by jonschlinkert** [comment]
unfortunately since `.insert` is sync, you would need to use a try/catch to handle the error (assuming you want to be able to ignore it or something). of courses you could always wrap it in a try/catch inside an async function.

we could consider making `.insert` async, then add an `.insertSync` method. then we can just pass the error in the callback instead of throwing. 

thoughts?

**Comment by shd101wyy** [comment]
Thanks for your reply. 

I have solved this problem by modifying my script so that the exception is avoided.
