### ISSUE TITLE
link headings (not exactly bug)

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/markdown-toc#54]
It may be wanted, but for me not make sense. Actual working example

```js
'use strict'

var toc = require('markdown-toc')
var res = toc('# API\n ## [letta](./index.js#L14)\nfoo bar\n## BBB\n## [.promisify](./index.js#L37)\n## CCC\nfoo')

console.log(res.content)
```

gives

```
- [API](#api)
  * [[letta](./index.js#L14)](#-letta---indexjs-l14-)
  * [BBB](#bbb)
  * [[.promisify](./index.js#L37)](#-promisify---indexjs-l37-)
  * [CCC](#ccc)
```

so render like

- [API](#api)
 + [[letta](./index.js#L14)](#-letta---indexjs-l14-)
 + [BBB](#bbb)
 + [[.promisify](./index.js#L37)](#-promisify---indexjs-l37-)
 + [CCC](#ccc)

_(huh, strange why github renders it here so indented but nevermind, that's not the case)_

Are you noticing the `[[letta](./index.js#L14)](#-letta---indexjs-l14-)` thing? Which is not okey for table of contents. Because toc link will not redirect you to the section where's that heading, but to the link that heading redirects to, in case to `index.js` file.

**Comment by jonschlinkert** [comment]
> Because toc link will not redirect you to the section where's that heading, but to the link that heading redirects to, in case to `index.js` file.

But you're defining a link in your heading. So it's using the link as the bullet text. It's out of the scope of this lib to decide what you wanted the text to be. The best solution is for you to create a custom [linkify](https://github.com/jonschlinkert/markdown-toc#utility-functions) function that strips the junk out of your headings, or a [filter function](https://github.com/jonschlinkert/markdown-toc#optionsfilter) that removes headings that are badly formatted so you can use whatever practices you want.

closing since this isn't really a bug. but feel free to ask questions

**Comment by tunnckoCore** [comment]
Best solution but it's not possible currently in verb. I faced this thing before months when started testing 0.9.0, so I completely disabled the toc. And that's the main reason that I'm not using it, because my last heading in readmes is my name and some badges.
