### ISSUE TITLE
How to generate TOC in PDF created using markdown-pdf?

### ISSUE THREAD

**Issue by rkrejcii** [jonschlinkert/markdown-toc#69]
Hi.

I will be grateful for any hint how to use markdown-toc with [markdown-pdf](https://github.com/alanshaw/markdown-pdf) for dynamic table of content insertion using [`toc.insert()`](https://github.com/jonschlinkert/markdown-toc#tocinsert) method.

The problem is that as far as I understand the logic, [`preProcessMd`](https://github.com/alanshaw/markdown-pdf#transform-markdown-before-conversion) works with streams, but `toc.insert` needs to process full Markdown file first (to generate TOC and insert it in Markdown file on position defined by `<!-- toc -->` tag).

Thanks.

**Comment by doowb** [comment]
@rkrejcii looks like you can [pass in remarkable plugins](https://github.com/alanshaw/markdown-pdf#optionsremarkableplugins) so  you should be able to do something like this:

```js
var markdownpdf = require('markdown-pdf');
var toc = require('markdown-toc');
var options = {
  remarkable: {
    plugins: [toc.plugin({ ... })]
  }
};

markdownpdf(options).from("/path/to/document.md").to("/path/to/document.pdf", function () {
  console.log("Done")
});
```

**Comment by gregorskii** [comment]
I am finding the links created when exported to PDF do not work. It's likely related to the parser used to create the PDF, where the internal markdown links are not converted to PDF links. I am using IA Writer to export, and also `markdown-pdf` on the CLI.

**Comment by burtonator** [comment]
Any resolution to this ? seems like it would be nice to get fixed.

**Comment by doowb** [comment]
@burtonator what's the issue? Are you running into an error? Do you have code you can show and the output that's not correct?

I gave an example showing how to use `remarkable` plugins with `markdown-pdf`. If there's an issue with that, it seems like it's an issue with `markdown-pdf`.

I'm going to close this since there wasn't a response from @rkrejcii.

@gregorskii and @burtonator if you still have an issue, please feel free to open a new issue with the code demonstrating the bug, otherwise, I'm don't know how to help.
