### ISSUE TITLE
Feature request: Flag to make ToC collapsable

### ISSUE THREAD

**Issue by corysimmons** [jonschlinkert/markdown-toc#75]
https://github.com/ahdinosaur/inu

^ pretty sweet

**Comment by jonschlinkert** [comment]
Yeah I just saw that in another project that had a FAQ on the readme, I wish I could remember where that was. it is indeed a pretty sweet idea. I think we'd just need to add rendering options, which means we should probably do some slight reorganizing of the functions that generate the list, so that it's more generalized and easier to customize the output. 

I'd be open to a pr, or I can take a stab at it when I get some time, but it probably won't be a priority. 

thanks, great idea!

**Comment by corysimmons** [comment]
I'd PR but I'm awwwwfffffffuulllllyyyyy lazy.

It's not a huge deal for me either. I just stumbled upon both your repos back-to-back and was like "this would be nice" so figured I'd open an issue in case someone else wanted to tackle it. It should be pretty simple tbh.

**Comment by SheetJSDev** [comment]
@corysimmons GH will do the right thing if you manually add the wrapper around `<!-- toc -->`:

```diff
+<details>
+       <summary>Table of Contents</summary>
+
 <!-- toc -->
+</details>
```

**Comment by corysimmons** [comment]
@SheetJSDev Ahh, sorry for this getting lost. Glad I stumbled on your solution. Simple and does the job! Maybe we could just add this to the README for others wanting markdown-toc but not wanting it to consume everything above-the-fold.

**Comment by corysimmons** [comment]
Either way this can be closed as I'm sure someone will stumble upon your tip if they're looking.

**Comment by SheetJSDev** [comment]
@corysimmons I would suggest adding it to the project wiki: https://github.com/jonschlinkert/markdown-toc/wiki just make a new page.

**Comment by corysimmons** [comment]
@SheetJSDev https://github.com/jonschlinkert/markdown-toc/wiki/Tips-and-Tricks done
