### ISSUE TITLE
Does not work with custom anchor id

### ISSUE THREAD

**Issue by CaledoniaProject** [jonschlinkert/markdown-toc#97]
It seems like markdown-toc does not recognize the `### title {#id}` syntax, can you fix that?

I've tried the following and it works for me:

In the linkify function, match the `{#id}` syntax and create the correct HTML tag

```
function linkify(ele, opts) {
  if (ele && ele.content) {
    var text = titleize(ele.content, opts);
    var slug = slugify(ele.content, opts);

    if (opts && typeof opts.linkify === 'function') {
      return opts.linkify(ele, text, slug, opts);
    }
    ele.content = utils.mdlink(text, '#' + slug);
    var match = /(.*)\s*{(#[^}]+)}/.exec(text);
    if (match) {
//        console.log (text)
        ele.content = '<a href="' + match[2] + '">' + match[1] + '</a>'
    }
  }
  return ele;
}
```

**Comment by doowb** [comment]
Hi @CaledoniaProject 

> custom anchor id

Is this part of the commonmark spec, or a custom syntax that you use?

If it's a custom syntax that you use, then you can pass in a `linkify` function on the `options` to modify the `ele.content`.

If it's part of the spec, then a PR would be appreciated. I think the PR would be passing different `text` and `slug` arguments to `utils.mdlink` instead of creating the link from scratch.

**Comment by CaledoniaProject** [comment]
It looks like a standard syntax

1. https://github.com/GitbookIO/gitbook/issues/1781
2. https://github.com/GitbookIO/gitbook/blob/master/docs/syntax/markdown.md

**Comment by doowb** [comment]
@CaledoniaProject that's a custom Gitbook syntax, it's not part of the [commonmark spec](http://spec.commonmark.org/0.28/).

You can pass a `.linkify` option to modify how the TOC links are created to enable that feature, but you'll also need another plugin to modify the header to give it an `id` attribute. That's out of the scope of this module, but since this module can be used as a [remarkable](https://github.com/jonschlinkert/remarkable) [plugin](https://github.com/jonschlinkert/markdown-toc#tocplugin), I can see another plugin be used in combination to achieve what you want.

**Comment by CaledoniaProject** [comment]
Thanks for pointing out. I've just published that as a new gitbook module 

https://github.com/CaledoniaProject/gitbook-plugin-toc-ng
